"""
In-memory pending action session store.

Stores voice sessions keyed by sessionId (UUID generated by frontend).
Each session holds:
- The InventoryIntent from the AI
- The ProductMatch from the search service
- The ProposedAction ready to execute
- A creation timestamp for TTL expiry
- An idempotency key for the confirm step

TTL: sessions expire after settings.SESSION_TTL_SECONDS (default 5 min).
Idempotency: once a session is confirmed it is marked as completed and
any duplicate confirm within 60 seconds is rejected.
"""
import time
import logging
from typing import Optional
from models.voice import InventoryIntent, ProductMatch, ProposedAction
from config import settings

logger = logging.getLogger(__name__)


class PendingSession:
    __slots__ = (
        "session_id", "intent", "product_match", "proposed_action",
        "created_at", "confirmed", "confirmed_at", "transaction_id"
    )

    def __init__(
        self,
        session_id: str,
        intent: InventoryIntent,
        product_match: ProductMatch,
        proposed_action: ProposedAction,
    ):
        self.session_id = session_id
        self.intent = intent
        self.product_match = product_match
        self.proposed_action = proposed_action
        self.created_at = time.time()
        self.confirmed = False
        self.confirmed_at: Optional[float] = None
        self.transaction_id: Optional[str] = None

    def is_expired(self) -> bool:
        return time.time() - self.created_at > settings.session_ttl_seconds

    def is_duplicate_confirm(self) -> bool:
        if not self.confirmed:
            return False
        # Allow re-show of success within 60s
        return (time.time() - (self.confirmed_at or 0)) < 60


# Global in-memory store
_sessions: dict[str, PendingSession] = {}


def store_session(session: PendingSession) -> None:
    _cleanup_expired()
    _sessions[session.session_id] = session


def get_session(session_id: str) -> Optional[PendingSession]:
    session = _sessions.get(session_id)
    if session is None:
        return None
    if session.is_expired():
        del _sessions[session_id]
        logger.info(f"Session {session_id} expired")
        return None
    return session


def mark_confirmed(session_id: str, transaction_id: str) -> None:
    session = _sessions.get(session_id)
    if session:
        session.confirmed = True
        session.confirmed_at = time.time()
        session.transaction_id = transaction_id


def clear_session(session_id: str) -> None:
    _sessions.pop(session_id, None)


def _cleanup_expired() -> None:
    expired = [sid for sid, s in _sessions.items() if s.is_expired()]
    for sid in expired:
        del _sessions[sid]
    if expired:
        logger.debug(f"Cleaned up {len(expired)} expired sessions")
